import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { initDb, getDb } from '../lib/db.mjs';
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'coread-browser-tests-'));
process.env.COREAD_DB = path.join(directory, 'isolated.db');
process.env.COREAD_PORT = '43183';
process.env.COREAD_HOST = '127.0.0.1';
initDb(process.env.COREAD_DB);
const db = getDb();
db.prepare('INSERT INTO books (id, title, total_paragraphs) VALUES (1, ?, 80)').run('可靠性测试书');
const insert = db.prepare('INSERT INTO book_paragraphs (book_id, idx, content) VALUES (1, ?, ?)');
for (let i = 0; i < 80; i++) insert.run(i * 3, `段落 ${i}。` + '阅读时可以在同一页停留很久，段落位置应当与屏幕页码保持独立。'.repeat(12));
db.prepare('INSERT INTO book_progress (book_id, page, paragraph_offset) VALUES (1, 30, 60)').run();
db.close();
process.on('exit', () => fs.rmSync(directory, { recursive: true, force: true }));
process.on('SIGTERM', () => process.exit(0));
process.on('SIGINT', () => process.exit(0));
await import('../server.mjs');
